'use client'

import React from 'react'
import { Document, Page, Text, View, StyleSheet, pdf } from '@react-pdf/renderer'
import type { IkigaiResults } from '@/lib/types'

const styles = StyleSheet.create({
  page: { padding: 48, fontFamily: 'Helvetica', backgroundColor: '#FFF9FA' },
  header: { marginBottom: 32, borderBottomWidth: 2, borderBottomColor: '#FFB7C5', paddingBottom: 16 },
  title: { fontSize: 28, fontWeight: 'bold', color: '#2D1B22', marginBottom: 4 },
  subtitle: { fontSize: 12, color: 'rgba(45,27,34,0.5)' },
  section: { marginBottom: 24 },
  label: { fontSize: 9, color: '#FF8DA1', textTransform: 'uppercase', letterSpacing: 1.5, marginBottom: 8 },
  heading: { fontSize: 16, fontWeight: 'bold', color: '#2D1B22', marginBottom: 8 },
  body: { fontSize: 11, color: '#2D1B22', lineHeight: 1.6, marginBottom: 8 },
  card: {
    backgroundColor: '#FFF5F7',
    padding: 12,
    borderRadius: 8,
    marginBottom: 8,
    borderLeftWidth: 3,
    borderLeftColor: '#FFB7C5',
  },
  footer: {
    position: 'absolute',
    bottom: 32,
    left: 48,
    right: 48,
    borderTopWidth: 1,
    borderTopColor: '#e5e5e5',
    paddingTop: 12,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  footerText: { fontSize: 9, color: '#8a8a7a' },
})

function IkigaiReportDocument({ results }: { results: IkigaiResults }) {
  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <View style={styles.header}>
          <Text style={styles.title}>Your Ikigai Report</Text>
          <Text style={styles.subtitle}>Generated by Daniel Paul · danielpaul.ai</Text>
        </View>

        <View style={styles.section}>
          <Text style={styles.label}>Your Ikigai</Text>
          <Text style={styles.body}>{results.ikigaiStatement}</Text>
        </View>

        <View style={styles.section}>
          <Text style={styles.label}>Your Archetype</Text>
          <Text style={styles.heading}>{results.archetype.name}</Text>
          <Text style={styles.body}>{results.archetype.tagline}</Text>
          <Text style={styles.body}>{results.archetype.description}</Text>
          <View style={styles.card}>
            <Text style={styles.body}>Growth edge: {results.archetype.watchOut}</Text>
          </View>
        </View>

        {results.monetizationStrategies.map((s, i) => (
          <View key={i} style={styles.card}>
            <Text style={styles.heading}>
              {s.icon} {s.title}
            </Text>
            <Text style={styles.body}>{s.description}</Text>
            <Text style={styles.body}>First offer: {s.firstOffer}</Text>
            <Text style={styles.body}>Income potential: {s.incomeRange}</Text>
          </View>
        ))}

        <View style={styles.section}>
          <Text style={styles.label}>Your First Step This Week</Text>
          <Text style={styles.body}>{results.ninetyDayStep}</Text>
        </View>

        <View style={styles.section}>
          <Text style={styles.body}>{results.closingMessage}</Text>
        </View>

        <View style={styles.footer} fixed>
          <Text style={styles.footerText}>Daniel Paul · danielpaul.ai</Text>
          <Text style={styles.footerText}>newsletter.purelypersonal.ai</Text>
          <Text style={styles.footerText}>linkedin.com/in/danielpaulai</Text>
        </View>
      </Page>
    </Document>
  )
}

export async function getIkigaiPdfBlob(results: IkigaiResults): Promise<Blob> {
  return pdf(<IkigaiReportDocument results={results} />).toBlob()
}

export async function downloadIkigaiPDF(results: IkigaiResults) {
  const blob = await getIkigaiPdfBlob(results)
  const url = URL.createObjectURL(blob)
  const link = document.createElement('a')
  link.href = url
  link.download = 'my-ikigai-report-danielpaul.pdf'
  document.body.appendChild(link)
  link.click()
  document.body.removeChild(link)
  URL.revokeObjectURL(url)
}
