'use client'

import React from 'react'
import { Document, Page, Text, View, StyleSheet, pdf } from '@react-pdf/renderer'
import type { IkigaiResults } from '@/lib/types'

const c = {
  cream: '#FFF9FA',
  cream2: '#FFF5F7',
  plum: '#2D1B22',
  plumLight: 'rgba(45,27,34,0.5)',
  pink: '#FFB7C5',
  pink2: '#FF8DA1',
  border: '#e5e5e5',
}

const styles = StyleSheet.create({
  page: { padding: 48, paddingBottom: 64, fontFamily: 'Helvetica', backgroundColor: c.cream },
  header: { marginBottom: 28, borderBottomWidth: 2, borderBottomColor: c.pink, paddingBottom: 14 },
  title: { fontSize: 26, fontWeight: 'bold', color: c.plum, marginBottom: 4 },
  subtitle: { fontSize: 10, color: c.plumLight },
  section: { marginBottom: 20 },
  label: { fontSize: 8, color: c.pink2, textTransform: 'uppercase', letterSpacing: 1.8, marginBottom: 6 },
  heading: { fontSize: 15, fontWeight: 'bold', color: c.plum, marginBottom: 6 },
  subheading: { fontSize: 12, fontWeight: 'bold', color: c.plum, marginBottom: 4 },
  body: { fontSize: 10, color: c.plum, lineHeight: 1.6, marginBottom: 6 },
  bodyLight: { fontSize: 10, color: c.plumLight, lineHeight: 1.6, marginBottom: 4 },
  card: {
    backgroundColor: c.cream2,
    padding: 10,
    borderRadius: 6,
    marginBottom: 8,
    borderLeftWidth: 3,
    borderLeftColor: c.pink,
  },
  cardNoBorder: {
    backgroundColor: c.cream2,
    padding: 10,
    borderRadius: 6,
    marginBottom: 6,
  },
  chip: {
    fontSize: 8,
    color: c.pink2,
    backgroundColor: c.cream2,
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 12,
    marginRight: 6,
    marginBottom: 4,
  },
  chipRow: { flexDirection: 'row', flexWrap: 'wrap', marginBottom: 6 },
  circleGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  circleCard: {
    width: '48%',
    backgroundColor: c.cream2,
    padding: 10,
    borderRadius: 6,
    marginBottom: 8,
  },
  circleLabel: { fontSize: 8, color: c.pink2, textTransform: 'uppercase', letterSpacing: 1.2, marginBottom: 4, fontWeight: 'bold' },
  metaBadge: { fontSize: 8, color: c.plumLight, marginRight: 12 },
  metaRow: { flexDirection: 'row', marginBottom: 6 },
  footer: {
    position: 'absolute',
    bottom: 28,
    left: 48,
    right: 48,
    borderTopWidth: 1,
    borderTopColor: c.border,
    paddingTop: 10,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  footerText: { fontSize: 8, color: c.plumLight },
})

function IkigaiReportDocument({ results }: { results: IkigaiResults }) {
  const r = results

  return (
    <Document>
      {/* Page 1: Statement + Archetype + Circles */}
      <Page size="A4" style={styles.page} wrap>
        <View style={styles.header}>
          <Text style={styles.title}>Your Ikigai Report</Text>
          <Text style={styles.subtitle}>Generated by Daniel Paul · danielpaul.ai</Text>
        </View>

        <View style={styles.section}>
          <Text style={styles.label}>Your Ikigai</Text>
          <Text style={styles.body}>{r.ikigaiStatement}</Text>
        </View>

        <View style={styles.section}>
          <Text style={styles.label}>Your Archetype</Text>
          <Text style={styles.heading}>{r.archetype.name}</Text>
          <Text style={styles.bodyLight}>{r.archetype.tagline}</Text>
          <Text style={styles.body}>{r.archetype.description}</Text>

          {r.archetype.strengths.length > 0 && (
            <View style={styles.chipRow}>
              {r.archetype.strengths.map((s) => (
                <Text key={s} style={styles.chip}>{s}</Text>
              ))}
            </View>
          )}

          {r.archetype.watchOut ? (
            <View style={styles.card}>
              <Text style={styles.body}>Growth edge: {r.archetype.watchOut}</Text>
            </View>
          ) : null}
        </View>

        <View style={styles.section}>
          <Text style={styles.label}>Your Four Circles</Text>
          <View style={styles.circleGrid}>
            <View style={styles.circleCard}>
              <Text style={styles.circleLabel}>What You Love</Text>
              <Text style={styles.body}>{r.circleInsights.love}</Text>
            </View>
            <View style={styles.circleCard}>
              <Text style={styles.circleLabel}>What You&apos;re Good At</Text>
              <Text style={styles.body}>{r.circleInsights.skills}</Text>
            </View>
            <View style={styles.circleCard}>
              <Text style={styles.circleLabel}>What the World Needs</Text>
              <Text style={styles.body}>{r.circleInsights.mission}</Text>
            </View>
            <View style={styles.circleCard}>
              <Text style={styles.circleLabel}>What You Can Be Paid For</Text>
              <Text style={styles.body}>{r.circleInsights.profession}</Text>
            </View>
          </View>
        </View>

        <View style={styles.footer} fixed>
          <Text style={styles.footerText}>Daniel Paul · danielpaul.ai</Text>
          <Text style={styles.footerText}>newsletter.purelypersonal.ai</Text>
          <Text style={styles.footerText}>linkedin.com/in/danielpaulai</Text>
        </View>
      </Page>

      {/* Page 2: Monetization + First Step + Closing */}
      <Page size="A4" style={styles.page} wrap>
        <View style={styles.section}>
          <Text style={styles.label}>How to Monetize Your Ikigai</Text>
          {r.monetizationStrategies.map((s, i) => (
            <View key={i} style={styles.card}>
              <Text style={styles.subheading}>{s.title}</Text>
              <View style={styles.metaRow}>
                <Text style={styles.metaBadge}>Time to revenue: {s.timeToRevenue}</Text>
                <Text style={styles.metaBadge}>Income range: {s.incomeRange}</Text>
              </View>
              <Text style={styles.body}>{s.description}</Text>
              <Text style={{ ...styles.body, color: c.pink2, fontWeight: 'bold' }}>First offer: {s.firstOffer}</Text>
            </View>
          ))}
        </View>

        <View style={styles.section}>
          <Text style={styles.label}>Your First Step This Week</Text>
          <View style={styles.card}>
            <Text style={styles.body}>{r.ninetyDayStep}</Text>
          </View>
        </View>

        <View style={styles.section}>
          <Text style={styles.body}>{r.closingMessage}</Text>
        </View>

        <View style={styles.footer} fixed>
          <Text style={styles.footerText}>Daniel Paul · danielpaul.ai</Text>
          <Text style={styles.footerText}>newsletter.purelypersonal.ai</Text>
          <Text style={styles.footerText}>linkedin.com/in/danielpaulai</Text>
        </View>
      </Page>
    </Document>
  )
}

export async function getIkigaiPdfBlob(results: IkigaiResults): Promise<Blob> {
  return pdf(<IkigaiReportDocument results={results} />).toBlob()
}

export async function downloadIkigaiPDF(results: IkigaiResults) {
  const blob = await getIkigaiPdfBlob(results)
  const url = URL.createObjectURL(blob)
  const link = document.createElement('a')
  link.href = url
  link.download = 'my-ikigai-report-danielpaul.pdf'
  document.body.appendChild(link)
  link.click()
  document.body.removeChild(link)
  URL.revokeObjectURL(url)
}
